### PR TITLE
Migrate to vue-dapp v1

### PR DESCRIPTION
**Pull request by johnson86tw**
## Migration process
1. add `~/store/ethers.ts`
2. remove `useWallet` in `NavbarDesktop`
3. replace all `'vue-dapp'` with `'~/store/ethers.ts'`
4. update `default.vue`

## `default.vue` (potential issue might lie here)
- Because we cannot use `methods` in `setup` function, I moved these 5 functions from `methods` to `setup`
```
orbisLogout,
fetchUserDomain,
fetchActivityPoints,
fetchChatTokenBalance,
getOrbisDids,
```
- Some logic was originally written within the `watch`, including `address`, `chainId`, and `isActivated`. I've moved them to `watchWalletChanged`, `watchDisconnect`, and `watchAddressChanged`.

## Cannot uninstall deprecated vue-dapp
- If I uninstall `vue-dapp@0.6.2`, when running `npm run generate`, it will fail with the following error. So at the moment, I think we should remain the old one..

```bash
❯ npm run generate

> generate
> nuxt generate

Nuxi 3.0.0                                                                                                                                         15:31:12
Nuxt 3.0.0 with Nitro 1.0.0                                                                                                                        15:31:12

 WARN  Using experimental payload extraction for full-static output. You can opt-out by setting experimental.payloadExtraction to false.           15:31:13


 WARN  Browserslist: caniuse-lite is outdated. Please run:                                                                                         15:31:13
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme


 ERROR  'EventEmitter' is not exported by __vite-browser-external, imported by node_modules/@walletconnect/jsonrpc-provider/dist/esm/provider.js   15:31:18
file: /Users/johnson/iggy-demo/node_modules/@walletconnect/jsonrpc-provider/dist/esm/provider.js:1:9
1: import { EventEmitter } from "events";
            ^
2: import { IJsonRpcProvider, isJsonRpcResponse, formatJsonRpcRequest, isJsonRpcError, getBigIntRpcId, } from "@walletconnect/jsonrpc-utils";
3: export class JsonRpcProvider extends IJsonRpcProvider {


 ERROR  'EventEmitter' is not exported by __vite-browser-external, imported by node_modules/@walletconnect/jsonrpc-provider/dist/esm/provider.js   15:31:18

  at error (node_modules/rollup/dist/es/shared/rollup.js:1858:30)
  at Module.error (node_modules/rollup/dist/es/shared/rollup.js:12429:16)
  at Module.traceVariable (node_modules/rollup/dist/es/shared/rollup.js:12788:29)
  at ModuleScope.findVariable (node_modules/rollup/dist/es/shared/rollup.js:11440:39)
  at ChildScope.findVariable (node_modules/rollup/dist/es/shared/rollup.js:6372:38)
  at ClassBodyScope.findVariable (node_modules/rollup/dist/es/shared/rollup.js:6372:38)
  at ChildScope.findVariable (node_modules/rollup/dist/es/shared/rollup.js:6372:38)
  at FunctionScope.findVariable (node_modules/rollup/dist/es/shared/rollup.js:6372:38)
  at ChildScope.findVariable (node_modules/rollup/dist/es/shared/rollup.js:6372:38)
  at Identifier.bind (node_modules/rollup/dist/es/shared/rollup.js:7439:40)
```

### CODE REVIEW

**Comment by tempe-techie** [comment]
@johnson86tw One issue that I've found is that if I want to click on another user's profile (click on his username in chat, or go to that user's profile via Find User), I get an error. Error is very likely in the PunkProfile.vue component, just don't know where exactly.

**Comment by johnson86tw** [comment]
@tempe-techie I found the error in `PunkProfile.vue` caused by vue-dapp's `shortenAddress` function.

It threw an error because `uAddress` is falsy and `shortenAddress` didn't handle the situation properly.

```
{{ shortenAddress(uAddress) }} // error
{{ uAddress && shortenAddress(uAddress) }} // success
```

I updated vue-dapp to v1.4.3 to handle the falsy issue and applied it in the iggy-demo.

**Comment by tempe-techie** [comment]
@johnson86tw I'm still getting this error when trying to go to user's profile page:

```bash
TypeError: Cannot read properties of undefined (reading 'slice')
    at Proxy.Ee (chunk-RACMK4RG.js?v=b2ba3167:134:12)
    at Proxy._sfc_render (PunkProfile.vue:709:1)
    at renderComponentRoot (chunk-E27EQVC6.js?v=b2ba3167:2336:17)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-E27EQVC6.js?v=b2ba3167:7323:46)
    at ReactiveEffect.run (chunk-E27EQVC6.js?v=b2ba3167:444:19)
    at instance.update (chunk-E27EQVC6.js?v=b2ba3167:7451:17)
    at setupRenderEffect (chunk-E27EQVC6.js?v=b2ba3167:7461:5)
    at mountComponent (chunk-E27EQVC6.js?v=b2ba3167:7236:7)
    at processComponent (chunk-E27EQVC6.js?v=b2ba3167:7190:9)
    at patch (chunk-E27EQVC6.js?v=b2ba3167:6685:11)
```

I did update to v1.4.3, but the problem remains.

**Comment by tempe-techie** [comment]
@johnson86tw I also noticed that if I delete `node_modules` folder and run `npm i` again, I get an error. So npm packages cannot be installed at all. Can you please check what's wrong?

**Comment by johnson86tw** [comment]
@tempe-techie Hey, Let me try to help you resolve this. I cloned the project on my computer and another Ubuntu machine, and set it to commit `93a091dc325db5749df652b5f180b75f64a9abf1` for testing, I couldn't reproduce the `TypeError: Cannot read properties of undefined (reading 'slice')` issue. 

I suspect it might be due to unsuccessful installation of your npm packages. 

Could you please provide the log from when you run `npm i`, as well as your current Node.js version?

**Comment by tempe-techie** [comment]
> your current Node.js version?

I used v22, but switching to v18 helped solve this issue, thanks!

**Pull request merged**
